### PR TITLE
wdi/Fix Replace material tailwind framework

### PR DESCRIPTION
**Pull request by i-mora**
# Changelog
- [ ] `@material-tailwind/html^2.2.2` replaces `@material-tailwind/react^2.1.8`
- [ ] [`prettier-plugin-tailwindcss`](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier) was introduced to increase consistency in dev

> [!IMPORTANT]
> There were some known issues caused by this migration but due to this is blocking some other stories, we'll address them later on in this story: https://trello.com/c/jcksbOJQ

### CODE REVIEW

**Review by yesi-aracawa — DISMISSED** [review]
As preview looks good, let's move forward to get a bigger advance

**Review by CesarSernaV — DISMISSED** [review]
LGTM

**Review by CesarSernaV — COMMENTED** [review]
LGTM

**Review by yesi-aracawa — APPROVED** [review]
:shipit:

**Review by CesarSernaV — APPROVED** [review]

**Pull request merged**
